### ISSUE TITLE
Script not working as expected

### ISSUE THREAD

**Issue by ribice** [rribeiro1/github-aws-commit-mirror#3]
I'm trying to set up repo mirroring from GitHub to CodeCommit. Few issues I'm facing:

1. The region is hard-coded `eu-central-1` - it doesn't use the `AWS_DEFAULT_REGION` env var.
2. I'd like to mirror repositories only from single organization, not all I have access to (including my private and other organizations). Now it's mirroring every repository.
3. Repositories get created on CodeCommit but they are empty. Part of the log is included below.

```
> Processing repository: dt 
--> Cloning repository dt to local storage 
Cloning into bare repository 'dt'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
--> Creating repository dt on AWS CodeCommit 
--> Pushing changes from repository dt to AWS CodeCommit 
sh: 1: cd: can't cd to dt
sh: 1: cd: can't cd to dt
--> Deleting repository dt from local storage 
```

**Comment by rribeiro1** [comment]
Hi, @ribice!
Thanks for opening the issue.
Yes, there is more room for improvement in the script. I am struggling to find time to improve this, but I appreciate any help you can give thought a PR.
